language: cpp
matrix:
  include:

    - os: osx
      compiler: gcc
      env: COMPILER='g++' CXXSTD='c++11'

    - os: osx
      compiler: clang
      env: COMPILER='clang++' CXXSTD='c++11'



dist: trusty
sudo: false

script: 
  mkdir build && cd build && cmake -DPHMAP_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=${COMPILER} -DCXXFLAGS="-std=${CXXSTD}" .. && cmake --build . && make test
