name: phmap CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        configs: [Release]
        compiler: [gcc, clang]
        flags: [-std=c++11, -std=c++17]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build and test
      env:
        CXX: ${{ matrix.compiler }}
        CXXFLAGS: ${{ matrix.flags }}
      run: |
        mkdir build && cd build && cmake -DPHMAP_BUILD_TESTS=ON -DPHMAP_BUILD_EXAMPLES=ON -DCMAKE_CXX_COMPILER=${CXX} -DCXXFLAGS="${CXXFLAGS}" .. && cmake --build . && make test
