name: Windows

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        flags: ["/std:c++11", "/std:c++latest"]
        optimize: [/O2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build and test
      env:
        CXX: ${{ matrix.compiler }}
        CXXFLAGS: ${{ matrix.flags }} ${{ matrix.optimize }}
      run: |
        mkdir build && cd build && cmake -DPHMAP_BUILD_TESTS=ON -DPHMAP_BUILD_EXAMPLES=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .. && cmake --build . && cmake --target RUN_TESTS
